### ISSUE TITLE
Error attempting to register function

### ISSUE THREAD

**Issue by paulxuca** [serverless/serverless-event-gateway-plugin#49]
Hi there!

I'm currently using this plugin to integrate our workflow with a self hosted event-gateway, and running into issues when deploying our functions.

I get this error:
```
Couldn't register a function function-name. Error: Failed to register the function function-name due the error: Function doesn't validate. Validation error: "Key: 'Function.Provider.Type' Error:Field validation for 'Type' failed on the 'required' tag".
```

This looks like an issue on the API side, with missing the type in the provider object (https://github.com/serverless/serverless-event-gateway-plugin/blob/master/src/index.js#L342). Is this only an issue on the self hosted version? Have yet to try it with the hosted version. I manually went in and added the type of function (awslambda) in the `provider` function and it works as expected.

Thanks for reading!

**Comment by alexdebrie** [comment]
Hey @paulxuca! Good call. We changed the signature for the RegisterFunction API in [this PR](https://github.com/serverless/event-gateway/pull/389) so that `type` is a top-level key, rather than contained in the `provider` block. Looks like we haven't cut a new release since then.

@mthenw should we cut a new release to incorporate recent changes?

**Comment by mthenw** [comment]
yeah, I will do that possibly today or tomorrow.

**Comment by mthenw** [comment]
Should be fixed now.
